coverage_service: coveralls
xcodeproj: ./Hamcrest.xcodeproj
workspace: ./Hamcrest.xcworkspace
scheme: Hamcrest-macOS
configuration: Debug
source_directory: Hamcrest
output_directory: ./coverage
ignore:
  - HamcrestTests/*
